### ISSUE TITLE
Run during development inside IDEA

### ISSUE THREAD

**Issue by jankod** [CRaC/example-spring-boot#3]
Is it possible to run during development within IDEA?

**Comment by sbaldin** [comment]
Try to download [jdk17-crac+5](https://github.com/CRaC/openjdk-builds/releases/tag/17-crac%2B5)), add it to inteliji and asign to the project, then run this project using forked jdk.

**Comment by jankod** [comment]
@sbaldin  I did that and nothing.
I was add -XX:CRaCCheckpointTo=cr parameter to JVM.

How do I start **jcmd** if I don't have a .jar, but I start it from the IDEA environment?

"jcmd target/spring-boot-0.0.1-SNAPSHOT.jar JDK.checkpoint"

**Comment by sbaldin** [comment]
Hm... So you can setup the run configuration in Inteliji that will launch your jar file with any params what you want, but I am not sure why do you need it?
You can run your app as usual, using jdk with crac if you need a implement crac specific interfaces, debug it. After that you just build a jar run it with -XX:CRaCCheckpointTo=cr and make checkout.

**Comment by jankod** [comment]
I don't want to use jar, because I want to run the application from the IDE, during development.

If I try without .jar, and run jcmd 25226 JDK.checkpoint I get this exception:
```
jdk.crac.CheckpointException
at java.base/jdk.crac.Core.checkpointRestore1(Core.java:141)
at java.base/jdk.crac.Core.checkpointRestore(Core.java:246)
at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:262)
Suppressed: jdk.crac.impl.CheckpointOpenSocketException: tcp6 localAddr ::ffff:127.0.0.1 localPort 47990 remoteAddr ::ffff:127.0.0.1 remotePort 45895
at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:91)
at java.base/jdk.crac.Core.checkpointRestore1(Core.java:145)
... 2 more
Suppressed: jdk.crac.impl.CheckpointOpenSocketException: tcp6 localAddr :: localPort 36239 remoteAddr :: remotePort 0
at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:91)
at java.base/jdk.crac.Core.checkpointRestore1(Core.java:145)
... 2 more
Suppressed: jdk.crac.impl.CheckpointOpenSocketException: tcp6 localAddr :: localPort 35729 remoteAddr :: remotePort 0
at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:91)
at java.base/jdk.crac.Core.checkpointRestore1(Core.java:145)
```
